- name: Update app
  hosts: all
  gather_facts: no
  tasks:
    - name: Stop old version
      command: pm2 stop src/app.js
      ignore_errors: yes
    - name: Extract new version
      unarchive:
        src: ../node/src.zip
        dest: ~/.
        owner: azureuser
        group: azureuser
    - name: Install dependencies
      command: npm install
    - name: Start new version
      command: pm2 start -a src/app.js
      environment:
        REDIS_URL: "{{ lookup('file', './redis_url') }}"
